### ISSUE TITLE
Animations page on Fabric website don't show animations

### ISSUE THREAD

**Issue by kollster** [OfficeDev/office-ui-fabric-core#1007]
On the Fabric website http://dev.office.com/fabric#/styles/animations , the animations don't show up when you click the animation boxes. This doesn't work in either Edge nor Chrome.

**Comment by Jahnp** [comment]
Hey @kollster, thanks! Not to sound like a broken record, but this is one of a few known documentation issues we'll be addressing very soon--we're working on a bunch of updates that should be rolling out over the next month or so. Though the code for the website is in the [Fabric-React](https://github.com/OfficeDev/office-ui-fabric-react) repo, I'll keep this issue open here since it concerns Fabric Core's grid class names.

**Comment by mikewheaton** [comment]
This has now been fixed: https://developer.microsoft.com/en-us/fabric#/styles/animations
