### ISSUE TITLE
Where can I find the svg files of the icons?

### ISSUE THREAD

**Issue by ayyash** [OfficeDev/office-ui-fabric-core#1008]
I searched Git for the svg font used for icons, or the svg files of the icons, couldn't find them anywhere, can someone please give me a hint? or post them for download?

**Comment by brannmar** [comment]
I've found them here. http://o365icons.cloudapp.net/
But no official website or download link.

**Comment by mikewheaton** [comment]
I don't think our license allows for distribution of SVG versions of the icons. @Jahnp may be able to confirm this, as he's been involved with recent license updates.

**Comment by anied** [comment]
Yeah, I'm perplexed about this as well.  Per the [Fabric Dev Page](https://developer.microsoft.com/en-us/fabric#/styles/brand-icons): **"Fabric provides these icons in both SVG and PNG formats."**  This led me to believe I would be able to access those SVG directly, but I can't find that anywhere.  I only require four SVG to use as icons for a file-type -- seems excessive to bring in a whole repository for those four icons.

The only thing I can think of is perhaps they are bundled in the downloadable Adobe XD file, which I have no way of opening.

**Comment by Jahnp** [comment]
Ah, sorry for the delay here! First and foremost, I'll be the first to note that our docs are not the most clear on this subject. I'll make a work item on us to clear some of this up.

A few clarifications:
- We do not currently provide nor plan to support static SVGs for the ["monoline" icons](https://developer.microsoft.com/en-us/fabric#/styles/icons). Those are provided to the Fabric team as a webfont from a core icons team within Microsoft, and I don't believe they plan to distribute those either. 
- I think it's down now as of this writing, but the site shared by @brannmar hosts a very old set of icons that use a mix of the "MDL1"/Metro design language *and* MDL2. Also, as far as I know, it is not actively maintained. In either case, I wouldn't look to this for a reliable, official icon resource.
  - I am working on an external version of the icon subsetting tool used to generate Fabric React's icons, which allow you to create custom webfont subsets and which are compatible with Fabric Core's icons. I can't commit to a specific timeline for this work, but the work is near complete. See https://github.com/OfficeDev/office-ui-fabric-react/issues/3218.
- @anied: You may have already noticed this, but the line about providing both SVG and PNG refers specifically to the *brand and file type icons* instead of the *monoline icons*. Those are available in both static SVG and PNG files, and have actually been both updated with new visuals and consolidated into the [@uifabric/file-type-icons](https://www.npmjs.com/package/@uifabric/file-type-icons) package in Fabric React. However, as I call out in #1088, these aren't reflected on the Fabric site right now--but it's on our backlog to fix this.
  - If you just need to grab specific SVG assets for the new icons, you can do so following this URL pattern, substituting `icon_name` with one of the names from the ]File Type Icon map](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/file-type-icons/src/FileTypeIconMap.ts): *https://static2.sharepointonline.com/files/fabric/assets/brand-icons/product/svg/{icon_name}_16x1.svg*
    - Do know that you'll still need to include the [assets license agreement](https://aka.ms/fabric-assets-license) to comply with the terms of using the icons.

I'm going to go ahead and close this issue for now, since we don't plan on addressing the core question of providing static SVGs for the icons.

**Comment by dannymcgee** [comment]
Hey @Jahnp, the company I work for makes applications that integrate with Microsoft services like SharePoint, and I'm working on updating our UI to fit into the Fabric aesthetic better. However, we're building these apps in Angular, not React, and getting the icons in (especially the multi-colored SVG icons) is proving to be a bigger hurdle than I had expected. It looks like the URL you posted in your last reply here is no longer working — is there an updated source for those SVGs that's not dependent on React? It looks like the [webfont kit](https://uifabricicons.azurewebsites.net/) will fit our needs nicely for the monoline icons, but we're incorporating a file explorer into our newest project, so I'd love to be able to use the Fabric file-type icons for that if at all possible.

**Comment by anied** [comment]
@dannymcgee - the link @Jahnp provided was an example link, so it didn't work because it included a "your icon name here" kind of substitution.  If you plug in the name of an icon you can find that it is still working:

https://static2.sharepointonline.com/files/fabric/assets/brand-icons/product/svg/word_16x1.svg

The downside here is that you need to know the name of the icon you're looking for.  I just _guessed_ that "word" would be one and it happened to work-- I don't know if there is perhaps a list somewhere that could be referenced to get the complete collection of icons available...

**Comment by kriede** [comment]
I figured out many of the available icons, Some are outdated (as of Feb 21, 2020) and many seem to be missing.
You can try my pen to see all icons that I have found:
https://codepen.io/kriede/pen/xxbbNVo

**Comment by SimranjitKaurMaan** [comment]
Is there any link to access the other set of icons like Chat? 

We are trying to use the SVG/PNG of the other icons available in [](https://uifabricicons.azurewebsites.net/).
