### ISSUE TITLE
baseFont not set on font mixins

### ISSUE THREAD

**Issue by casvaniersel** [OfficeDev/office-ui-fabric-core#1010]
Hi Team,

Switching from 4.1.0 to the latest 7.2.0 UI Fabric css file left me with a completely different font. A little research showed me that the font mixins in 4.1.0 include a baseFont and the new version does not.

`@mixin ms-font-su {
  @include ms-baseFont;
  font-size: $ms-font-size-su;
  font-weight: $ms-font-weight-light;
}`

now in 7.2.0 I'm missing the baseFont

`@mixin ms-font-su {
  font-size: $ms-font-size-su;
  font-weight: $ms-font-weight-light;
}`

**Comment by mikewheaton** [comment]
Hi @casvaniersel, as of [Fabric Core 6.0](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/6.0.0) the font family is set using the `ms-Fabric` wrapper component like so:

```
<div class="ms-Fabric">
    ... your app goes here
</div>
```

This makes it possible to provide options like the `ms-Fabric--selawik` class, which will update all of the text within your app to use the [Selawik web font](https://github.com/Microsoft/Selawik) as an alternative to Segoe UI. It also allows you to use a custom font in your application with a single override, rather than having to target every `ms-font-[size]` class independently.

**Comment by casvaniersel** [comment]
Hey @mikewheaton I totally missed this guidance! Thank you for helping out. Any idea when the documentation on dev.office.com will be updated?

**Comment by mikewheaton** [comment]
We're working on some big updates to the documentation site now. Apologies that we're so behind here.
