### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by johannes-z** [OfficeDev/office-ui-fabric-core#1019]
I was wondering about the license of [office-ui-fabric-core](https://github.com/OfficeDev/office-ui-fabric-core) and related projects/frameworks. The projects themselves are licensed under MIT, with exception of the fabrics assets. Is it legally ok to create a Vue.js open-source (MIT) port/counterpart of [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react) using [office-ui-fabric-core](https://github.com/OfficeDev/office-ui-fabric-core) and fabric assets? Similar to [ng-officeuifabric](https://github.com/ngOfficeUIFabric/ng-officeuifabric).
Thanks!

**Comment by Jahnp** [comment]
Hey @johannes-z, sorry for the delay! This is a great question. Yes, framework ports of any Fabric project are totally supported and encouraged. We'd love to see these kinds of projects take off since it's not certain we'd have bandwidth to drive them ourselves. 

I'm not a lawyer, but to expand on the licensing question a little: the only constraint to be aware of is the [Fabric assets license](https://aka.ms/fabric-assets-license), which covers scenarios and proper usage of Fabric's fonts and icons. Creating & publishing framework code that could deliver these assets like ng-officeuifabric is fine under the licensing agreement, since projects like that could be used to create Office Add-ins, SharePoint web parts, or other Office integrations. It's *publishing* and *marketing* the apps that would use those assets via a project like this that would fall under the scope of the license agreement.

Does that make sense?

**Comment by johannes-z** [comment]
Alright, thanks a lot for the clarification!
