### ISSUE TITLE
Inconsistent (Fill/Solid) icon naming

### ISSUE THREAD

**Issue by Danny-Engelman** [OfficeDev/office-ui-fabric-core#1025]
Working on using MouseOver states, 
found some inconsistencies in icon names, where I could **not** just add Solid to the iconname.

Using Chrome see: https://365csi.nl/toolkit/iconator/index.html
(and activate the "highlight solid/fill icons" checkbox in the lower right)

(background red) These icons end with 'Solid' but have no corresponding non-solid icon, or the naming convention (ends with Solid) does not match

What is the convention/distinction for (ending with) Solid (green) or Fill (red)?

GiftBoxSolid,GiftCard,Giftbox,GiftboxOpen; should it all be Box or box?

tia

**Comment by mikewheaton** [comment]
I reached out to the team who creates the icons and, while there may be a couple exceptions, the general distinction is that:
- **Solid** indicates an icon that is to be used on its own. These are often paired with a monoline version so that you can toggle between one and the other to indicate a state change. It is the *same size* as the monoline version.
    ![image](https://user-images.githubusercontent.com/1382445/31186797-8ee02342-a8e4-11e7-9bc4-2b7a85c436eb.png)
- **Fill** indicates an icon that's intended to be placed behind another icon, to fill in portions of the top icon. By combining two icons you can create a multi-color icon. These are *0.5px smaller* than the top layer to prevent color bleed.
    ![image](https://user-images.githubusercontent.com/1382445/31186950-130acb7c-a8e5-11e7-8d49-0a1bba36f7fa.png)
    ![image](https://user-images.githubusercontent.com/1382445/31186956-1ba5bd82-a8e5-11e7-82b3-7418e901ab18.png)

Hope that helps!
