### ISSUE TITLE
Property for single choice in people picker component

### ISSUE THREAD

**Issue by geogikk92** [OfficeDev/office-ui-fabric-core#1027]
I want to know property for single choice of this people picker component --> [HERE](https://dev.office.com/fabric#/components/peoplepicker)

**Comment by Jahnp** [comment]
Hi @geogikk92, it looks like this issue is for [Office UI Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/). Would you mind re-opening this issue there?

And, just to confirm, are you asking if there is a property that allows you to specify that a user can only select one person from the list of people, rather than multiple as you can today? If that's the case, while it may not be ideal, you could likely build this scenario yourself by toggling the `disabled` prop when the `items` count is greater than 0. You may be able to use `onChange` or `onItemSelected` to start this.

That said, this seems like a reasonable behavior to support, so it's possible that other Fabric React users would have a need for it as part of the contract.

In the short-term, I'm going to close this issue here since it belongs in the Fabric React repo. Thanks!
