### ISSUE TITLE
 Media Queries broken breakpoints [decimals of a pixel]

### ISSUE THREAD

**Issue by tom-daly** [OfficeDev/office-ui-fabric-core#1132]
related to Media Queries broken breakpoints #929 that was closed.

I believe that I am experiencing the same issue. There is a gap where both ms-hiddenMdUp and ms-hiddenSm show. This happens at every single other breakpoint when it falls in the decimal of a pixel range. I'm using ms-hiddenMdUp and ms-hiddenSm so I only see it a few times.

@media (max-width: 479px)

<style>…</style>
.ms-hiddenLgDown, .ms-hiddenMdDown, .ms-hiddenSm, .ms-hiddenXlDown, .ms-hiddenXxlDown {
display: none!important;
}

**_The gap is within the decimal of a pixel. So in chrome I'm measuring 479.091px .... that technically is between 479 < 479.091 < 480..._**

media (max-width: 639px) and (min-width: 480px)

<style>…</style>
.ms-hiddenLgDown, .ms-hiddenMd, .ms-hiddenMdDown, .ms-hiddenMdUp, .ms-hiddenXlDown, .ms-hiddenXxlDown {
display: none!important;
}

![image](https://user-images.githubusercontent.com/9259305/44415959-af74f300-a53f-11e8-89fa-21f6d7174fec.png)

![image](https://user-images.githubusercontent.com/9259305/44415968-b439a700-a53f-11e8-8599-6dfa29534588.png)

**Comment by mikewheaton** [comment]
Thank you for the detailed report and repro, @tom-daly.

I found an [article](http://damienclarke.me/code/posts/those-1px-gaps-between-media-queries-can-be-a-problem) that identifies the same issue. The simplest fix in our case is likely to update the media queries to use values like `639.999px`, so that the gap between that and `640px` is _very_ small and unlikely to be hit.

**Comment by tom-daly** [comment]
I've never had one of my bugs fixed before so thank you, you made my day
