### ISSUE TITLE
ComboBox cannot define the height of the callout and make it scrollable.

### ISSUE THREAD

**Issue by dingbx** [OfficeDev/office-ui-fabric-core#1164]
if I set the callout style to height:200 and overflow: auto, there will be two scrollbars because ms-Callout-main has another {height , overflow}. Is there a way to define the height of the ms-Callout-main?

**Comment by Jahnp** [comment]
Hi @dingbx , thank you for your question. It would seem this issue is better-suited for [Office UI Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/). If you feel this is a bug, please choose one of the [issue templates](https://github.com/OfficeDev/office-ui-fabric-react/issues/new/choose) and fill out the requested information to better help us help you.

That said, for questions like this, we recommend posting on StackOverflow and tagging them with [office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric). Providing a CodePen that illusrates what you're trying to do helps a ton. Thank you!
