### ISSUE TITLE
Some icons does not works when referring the css from the CDN

### ISSUE THREAD

**Issue by sharmajnu** [OfficeDev/office-ui-fabric-core#1197]
Hi,

I am referring the fabric core from CDN as mentioned in [getting started document](https://developer.microsoft.com/en-us/fabric#/get-started#fabric-core).

Some of the icons does not shows up for examples icons like Pdf, BulletedTreeList are not shown. 
Please check the [plunker](https://plnkr.co/edit/AJLxvTYjoFl445tlpB1F?p=preview) to see the problem.

Please guide on how to solve this issue, as this is a major show stopper for us.

**Comment by sharmajnu** [comment]
Thanks this is great help.

**Comment by sharmajnu** [comment]
Hi @Jahnp 
Any updates on this?

**Comment by Jahnp** [comment]
Hi @sharmajnu , big apologies for the delay here. It seems between the last release and now, `Mirrored` versions of `Calendar`, `DateTime`, and several other icons were added (you can see the full list [here](https://github.com/OfficeDev/office-ui-fabric-core/pull/1195)by searching for "Mirrored"), whereas before there may only have been non-`Mirrored` versions of those icons.

What this means is that in order for the icons to render, you need to have either `dir="rtl"` or `dir="ltr"` appended to `body`. I've modified your plunkr [with this fork](https://next.plnkr.co/edit/qew5H5X831yhhiC6) to show how this is done.

The reason for this is that the icon design team often produces 2 versions of an icon to optimize for directionality depending on the language: a left-to-right version and a right-to-left version. Rather than requiring users to manually swap the LTR with RTL icons depending on the language, we use directionality mixins to pivot off the `dir` attribute to automatically swap the Unicode value using the non-`Mirrored` classname as the base classname.

You can see the SCSS logic and reasoning for this here: https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_Icon.Mixins.scss#L66

I realize this is a bit unintuitive if you aren't appending a `dir` today—we can consider investing a fallback if one is not added. But to unblock yourself with existing releases, that's the best way forward.

**Comment by sharmajnu** [comment]
Hi @Jahnp 
Thanks for the reply, the answer you provided is sufficient for now.

Maybe in upcoming release it would be better to add the fallback when no sir as you mentioned.

Regards,
Deepak
