### ISSUE TITLE
Remove all colors from font classes/mixins.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-core#767]
The font mixins have color in them. It causes a lot of issues, please let's consider removing them. Otherwise even just consuming the mixins (not the classes) is difficult and we end up duplicating them elsewhere.

PR here:
https://github.com/OfficeDev/office-ui-fabric-core/pull/766

**Comment by mikewheaton** [comment]
I'm also not sure that baking in a default color (which is the same for every size on the type ramp) is useful. Including the weights make sense because we provide a recommended weight for each size, but with color it depends so much on context that you do end up overriding it often.

To avoid applying a color you can always use `ms-fontSize-s ms-fontWeight-regular`, but you lose the convenience of combining the weight and size together.

**Comment by mikewheaton** [comment]
We just discussed this in the a design meeting and determined that the default color _should_ remain in the CSS classes (e.g. `.ms-font-xl`). These classes are intended to help developers quickly style body text, where the default color is part of the design language.

It makes sense that, when building components, you'd want to use a mixin that applies the `font-size` and `font-weight` – two properties that are almost always found in the same combinations – without including a color.

That mixin would allow you to replace:

```
.MyComponent {
  font-size: $ms-font-size-xl;
  font-weight: $ms-font-weight-light;
}
```

With:

```
.MyComponent {
  @include ms-font-xl;
}
```

It's not a huge reduction in code, but it does help you to pick what is almost always the right weight for a given size.
