### ISSUE TITLE
DatePicker Issues

### ISSUE THREAD

**Issue by simkessy** [OfficeDev/office-ui-fabric-core#789]
Is there any validation we can apply to two datepickers? If I have a startDate and endDate picker, is it possible to prevent endDate from being less than startDate?

**Comment by ericthompson** [comment]
Thanks for dropping a note, @simkessy, but this Issue is related to one of the components that is now contained in the [Office UI Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) repo.

I can still answer your question, though :smile: 

We use the [pickadate](http://amsul.ca/pickadate.js/) input picker to power ours - the [API](http://amsul.ca/pickadate.js/api/) is available through Amsul's site. Feel free to file more issues in the JS repo if you have further questions.

**Comment by simkessy** [comment]
Thanks for the reply @ericthompson  but does this keep the same styling and functionality as Office Fabric?

**Comment by mikewheaton** [comment]
Yes, @simkessy, Fabric provides styling for the Pickadate date picker.
