### ISSUE TITLE
Where should I go to download the font file?

### ISSUE THREAD

**Issue by chenshuai2144** [OfficeDev/office-ui-fabric-core#807]
I loaded my font very slowly because I was in China.

**Comment by mikewheaton** [comment]
Unfortunately, due to licensing constraints we can't provide a copy of the Segoe UI web font. It must be referenced from the CDN. Are you also referencing Fabric Core (fabric.css) from the CDN? Or just the font?

**Comment by chenshuai2144** [comment]
fabric.css, I use  fabric icon but I loaded font very slowly.
Experience is not good.

https://appsforoffice.microsoft.com/fabric/fonts/icons/FabricMDL2Icons.woff  
This font loaded need 23s

**Comment by ericthompson** [comment]
We're currently looking into some server issues and will be trying to get improvements going soon. Unfortunately, we're a bit limited at the moment since, as @mikewheaton said, we can't provide a copy of the font for download.

Please expect improvements within the next month, and we apologize for the inconvenience!

**Comment by codepunkt** [comment]
Microsoft has been a good open source citizen lately. What's preventing you from also open sourcing this font/the icons under a commonly usable OSS license?
