### ISSUE TITLE
Unable to find the previous Office Fabric UI page and code

### ISSUE THREAD

**Issue by JyotsnaWadhwani** [OfficeDev/office-ui-fabric-core#810]
Hi,
I had been working on a SharePoint Application in which I used a few components of Office Fabric UI. Recently, I saw that you guys have changed your Office UI Fabric site. I am not able to find the previous Html and JS code for the components listed on the site. I have a few queries in reference to this:

1. Is there any release coming for only Office Fabric UI which does not involve React JS?
2. How can I access the older version of Office Fabric UI which didn't involve React JS?
3. Will all your further releases be only constrained to React JS?
4. Will there be Html and JS codes coming up for the present components like the Detail List, Callout, etc?
Kindly, help me with the following queries so that I can plan my work accordingly.

**Comment by sjclemmy** [comment]
You'll find the documentation in your current installation of the office-ui-fabric dependency:
office-ui-fabric > dist > documentation.

**Comment by ericthompson** [comment]
Thanks for the providing some pointers, @sjclemmy!

The Fabric sub-projects are split between:
- [Fabric Core](https://github.com/OfficeDev/Office-UI-Fabric) - the core, JS framework independent set of base styles (colors, icons type, the grid, and more)
- [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) - the presentation-focused, simpler components that don't use a framework, but do use [TypeScript](https://www.typescriptlang.org/) that compiles down to vanilla JS
- [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react) - React-based implementation of our components that is being used across multiple teams
- [Fabric iOS](https://github.com/OfficeDev/office-ui-fabric-ios) - Native Swift implementation of some core styling and components

A few months ago, we split the components out from the Fabric repository making Fabric JS (since there are now multiple implementations of the components). The Fabric JS project has already had other releases since splitting it off, so, although most of *our* work will be going to Fabric React for now, we'll continue to monitor the project, look at PRs, and see what sorts of usage the project gets. I would expect significantly more momentum behind the Fabric React project for a while as it continues to be used by modern SharePoint and other teams throughout the company.

At the moment, there are no plans to "port" new components like the DetailsList over to Fabric JS, but, if you have a request, please file an issue in the [Fabric JS repo](https://github.com/OfficeDev/office-ui-fabric-js/issues) and it will be added to the [Fabric JS Trello board](https://trello.com/b/wq7oIK87/office-ui-fabric-js-requests) so we can track what folks want/need.

The last stable version of Fabric that included the components is [Fabric 2.6.1](https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/2.6.1) which you can still use (even if you're referencing the CDN). [We have some documentation that can help you get started with this version too](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/ghdocs/V2GETSTARTED.md). We're also looking into how to improve the documentation that @sjclemmy so nicely pointed you to 😄
