### ISSUE TITLE
Release Numbers?

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-core#821]
Releases in this project went from 4.1.0 to 2.6.2.  Was this intentional?  If so, it's going to cause some confusion when the project gets back to 3.x and 4.x again.

**Comment by Jahnp** [comment]
Hi @manndave, 2.6.2 was a patch for the 2.6.1 release, since we found a previously-undiscovered bug in that version that prevented compilation in new versions of Node. Since there are some users still using 2.6, we want to make sure they can at least build to view the local docs site :) We'll be getting back to our regularly-scheduled 4.x releases from here out.

**Comment by manndave** [comment]
OK, thanks @Jahnp.  The Releases page is a little confusing (showing 2.6.2 as "latest") but I suppose it will be easier/better once we get a new 4.x release.  Github doesn't seem to make it easy to maintain multiple "active" versions.  :-(

**Comment by Jahnp** [comment]
Yep, you've hit the nail on the head. The current "serial-only" system for releases is a bit confusing--would make a great feature request for GitHub. In the meantime, I've updated the release text for 2.6.2 to make it abundantly clear that this is just a patch release for 2.6.1--hopefully that will help clarify the intent.

If you don't mind, I'm going to go ahead and close this issue for now. Thanks again for calling this to our attention!
