### ISSUE TITLE
Any plans to move documentation from the website to the wiki?

### ISSUE THREAD

**Issue by gregdegruy** [OfficeDev/office-ui-fabric-core#838]

**Comment by mikewheaton** [comment]
This isn't something we've discussed. Are you wanting to contribute to the documentation? 😄

**Comment by gregdegruy** [comment]
I'd be happy to suggest edits as I work through the docs on my personal project, if I have edits I want to suggest for the website can I report them here?

**Comment by ericthompson** [comment]
@gregdegruy - you can absolutely report edits/bugs here. They'd be much appreciated 👍 

I'd love to know what areas of documentation you were thinking about making suggestions for:
 - Core Styles (icons, typography, colors, etc.)
 - Fabric React components
 - Fabric JS components
 - General info like Getting started or the Resources section

Thanks!

**Comment by gregdegruy** [comment]
Most likely feedback focused on the React component side, in terms of additional steps that could be added to the code snippet doc.

**Comment by ericthompson** [comment]
Cool! Thanks for the extra info. We've discussed making the documentation open source, but currently haven't been able to schedule that. This is very helpful in pushing us to do this 😄 

In the end, though, moving to the wiki isn't on our roadmap (since we'd just go open source instead), so closing for now.
