### ISSUE TITLE
Add support for Selawik as an alternative to Segoe UI web font

### ISSUE THREAD

**Issue by gautamsi** [OfficeDev/office-ui-fabric-core#852]
It would be helpful for community if Fabric team can use [Selawik](https://github.com/Microsoft/Selawik) as fallback approach where Segoe license has restriction. There is also a [Symbol](https://github.com/Microsoft/fonts) font which can be used along with Selawik. 

We can have wider adoption of this library and MDL2 outside of Office/MS linked usages. 

Looks like the development on the two project has stalled or not published to GitHub for over a year now. if Fabric team adopts these fonts, their further development can happen. It would be great contribution to open source community by Microsoft

**Comment by mikewheaton** [comment]
Related issue that was opened for Fabric React: [How can I avoid usage of fonts which have an MIT license?](https://github.com/OfficeDev/office-ui-fabric-react/issues/618)

**Comment by gautamsi** [comment]
I do see the explanation, I am working on some application which would complement Microsoft office but not directly integrating in Office add-in or so. there is good chance of this being caught in licensing terms. The Office fabric may have other use case without having to directly integrate in office product or launched from Office. I can have a web version of my app which is mobile friendly etc, at the same time using office design. There may be office add-in or not. I do not want to get caught in licensing glitch

**Comment by ericthompson** [comment]
Thanks for the extra info, @gautamsi. Let me reach out to some folks on my end and connect you with them to see if there are other options.

**Comment by lafe** [comment]
I would like this as well. The main blocker for the adoption of Office UI Fabric at the current customer is that we cannot use assets that are hosted online when we are developing an on premises solution. This means that we cannot use the OOTB Office UI Fabric as it loads the font assets from a Microsoft CDN. The solution was to use alternative fonts that can be hosted in our environment and customize the Office UI Fabric to use these assets. It's possible and relatively easy but it increases the maintenance effort as we have to update our fork constantly. It would be great, if such use cases can be made easier.

**Comment by mikewheaton** [comment]
To support Fabric being used without a CDN we're going to:

- Provide documentation on overriding the root `font-family` to one that uses only system-installed fonts, or web fonts hosted on your own server.
- Discuss with our legal team the possibility of allowing you to host a copy of the Segoe UI web font on your own server.

To allow the use of Fabric in non-Office scenarios not covered by the [assets license](https://aka.ms/fabric-assets-license) we're going to:

- Provide documentation on overriding the root `font-family` to use another font. This could be a system-installed font, a web font on your own server, or a web font from a service like [Google Fonts](https://fonts.google.com/) or [Typekit](https://typekit.com/).
- Investigate adding support for [Selawik](https://github.com/Microsoft/Selawik) into Fabric and hosting this on our CDN.

**Comment by gautamsi** [comment]
given that Selawik is OFL, can we not use them bundled in our package? or host on our own?

if there is progress on Selawik, that would definitely helpful to the community. 

Have you got any infromation on Symbol font I mentioned earlier?

**Comment by mikewheaton** [comment]
Replacing the icon font will be more challenging, as it likely contains many icons that aren't in the [open source alternative](https://github.com/Microsoft/fonts). We're going to investigate this but don't have a definite plan here yet. At a minimum we should document how to substitute the font and replace specific icons.

**Comment by Jahnp** [comment]
@gautamsi Yeah, given Selawik's license, you *should* be fine to bundle or host the files yourself. I can follow up with our font contact to double-check on this, as well as if there is any planned further development on Selawik (e.g. expanding character sets to match Segoe).

Agreed with @mikewheaton around concerns for substituting the OSS symbol font. Hypothetically it should be fine for cases where there are overlaps, but there's potential for bugs with sizing and positioning. While adding first-class CSS support would take some work, you should feel free to try using them--we'd love to know how they work for you.

**Comment by gautamsi** [comment]
I would be willing to extend the Symbol font, have limited knowledge on working with fonts, if there is build system documentation and any guideline provided on working with the OSS font in original repo, I would be happy to extend it as need basis and keep it aligned with the MDL2 font codes

**Comment by mikewheaton** [comment]
I've narrowed this issue specifically to adding Selawik as a built-in alternative to Segoe UI. A new issue (#871) has been created to cover documenting how to override the base `font-family` to avoid pulling Segoe UI from the CDN as usual.

**Comment by mikewheaton** [comment]
To follow up on an earlier comment, we've clarified with our legal team that the Fabric assets (Segoe UI web font, icon font, and brand icons) **can be hosted on your own server**. However, the terms of [the license](https://static2.sharepointonline.com/files/fabric/assets/license.txt) still apply so you must use these "for the purpose of developing for Office and other Office 365 endpoints including, but not limited to, Office Add-ins, SharePoint Web Parts, SharePoint Apps, and Custom Office 365 apps". If you are developing an app that falls outside of that scope, you must use an alternate font and icon set.

**Comment by lafe** [comment]
That is great news. Will the license be updated to clarify this use case or will there be another document that states it more explicitly? A lone Github comment might not be sufficient for the legal department at customers if the question should ever arise.

**Comment by showenx** [comment]
is it possible to include font file in the release package, and referenced locally from dist folder?

**Comment by Jahnp** [comment]
Hi @lafe: So sorry for the delay, I must've missed this question earlier. We've been working with our legal team on updating the documentation around the license to clarify these use cases. I don't have a timeline (we're working at the Speed of Legal), but believe us, we'd like this out soon :)

@showenx: We're looking into ways to support this scenario; I know it's a big deal from an engineering standpoint. Unfortunately, it's a bit challenging from a legal perspective due to the usage of these assets as part of Microsoft's brand, so I can't promise anything, but know that we want to enable this. We should have some news to share here before too long.

**Comment by CrmDev23** [comment]
Hi there
I'm also wondering if the Fabric assets can be used for Microsoft Business applications like Dynamics 365.
Thanks!

**Comment by mikewheaton** [comment]
@CrmDev23 Yes, they can. The [assets license](https://static2.sharepointonline.com/files/fabric/assets/license.txt) covers "Office and other Office 365 endpoints including, but not limited to, Office Add-ins, SharePoint Web Parts, SharePoint Apps, and Custom Office 365 apps". While I'm not a lawyer, that should clearly cover Dynamics. :)

**Comment by CrmDev23** [comment]
Good to know. Thanks :+1:!

**Comment by LarsKemmann** [comment]
@mikewheaton I've been reviewing the verbiage of [the new assets license PDF](https://static2.sharepointonline.com/files/fabric/assets/microsoft_fabric_assets_license_agreement_sept092017.pdf) linked from the homepage. The clauses about O365 have been removed and it now requires use of the assets to be:

 > In connection with the use of a Microsoft API within the development of a software application, website, or product you create or a service you offer **designed to provide access or interact with a Microsoft service or application** (“Application”)

Given the part that I highlighted, I'm wondering if the possibility exists that I could use the assets in my application under the following constraints:

- While my app is not (yet) a "custom Office 365 app" (i.e., one that is launched from the O365 launcher), it could become so. The problem is that not all my customers have Office 365 so I can't actually design my app to require that for all users.
- My app does use Microsoft services; specifically, it is hosted in Azure and users do interact with Azure AD B2C/B2B.

Thanks!
~Lars

**Comment by LarsKemmann** [comment]
@mikewheaton Following up on this since this is still, from what I can see, a significant need. Developers have come to rely on having Microsoft's UI controls library as a starting point; not having that available now for web apps is a challenge, which Office UI Fabric is really well poised to address. You just need to call it "Microsoft UI Fabric" and clarify the licensing language. :-) Any hope of seeing at least the licensing piece be addressed, maybe at a significant upcoming conference? You would make a lot of enterprise developers _very_ happy.

**Comment by Jahnp** [comment]
Hi @LarsKemmann , sorry for the delay, I must have missed your original question. To confirm, yes, your app does indeed fall under the acceptable use cases described by the updated license verbiage. Fabric can indeed be used by web apps that live within, connect to, or build on Microsoft developer platforms and APIs. That was actually the motivation we had for going back to our legal team to revisit the agreement. 

Agreed that this could definitely be made more clear, though. Though I can't commit to specifics right now, I would expect to see us clarify this usage at an upcoming conference.

@manishgarg1 for visibility.

**Comment by LarsKemmann** [comment]
@Jahnp _**Thank you!!!**_ :-)
