### ISSUE TITLE
List component - where are the mixins as used in the demo

### ISSUE THREAD

**Issue by panigrah** [OfficeDev/office-ui-fabric-core#889]
I am trying to use the inbox example for the List component and having trouble with importing sccs files as described in the examples.
 
That example contains a css file List.Mail.Example.scss which imports common.sccs. I copied this css file over to my application, however it is unable to find the @import '../../../../common/common' and so the mixins are not available. 

How do I import these mixins into my app?

**Comment by panigrah** [comment]
Is this the right way to use it?

`@import '../../../node_modules/office-ui-fabric-react/dist/sass/Fabric.Common';`

**Comment by Jahnp** [comment]
Hi @panigrah, sorry for the delay. Just checking--are you still seeing this issue? Also, since you mention `office-ui-fabric-react`, did you intend for this to be opened in [the repo for that project](https://github.com/OfficeDev/office-ui-fabric-react/)? This repo is for tracking issues for Fabric's Core styles, not the React components.
