### ISSUE TITLE
Support (or at least published values) for unicode insertion

### ISSUE THREAD

**Issue by clechner77** [OfficeDev/office-ui-fabric-core#909]
Would be handy to be able to use the icons with unicode values and pseudo elements.  Perhaps there's a reference someone that I just missed.

**Comment by Jahnp** [comment]
Hi @clechner77, sorry for the delay here!

You should be able to do this today in one of several ways:

1. You can use the `ms-Icon` classes [documented here](https://dev.office.com/fabric#/styles/icons#implementation) directly in your HTML. This is the recommended approach here, since this guarantees that you're always using the correct character even if for some reason the Unicode value were to change down the line. Here's an example of this: 
```html
<i class="ms-Icon ms-Icon--MapPin" aria-hidden="true"></i>
```

2. If you're using SCSS, you can use the [Icon mixins](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_Icon.Mixins.scss) to inject the glyph you want on `::before` or `::after` pseudo elements. We actually use these to [populate the `ms-Icon` classes](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/_Icon.scss#L49).  An example of this might be:
```scss
.my-Icon::before { @include ms-Icon--MapPin; }
```

3. If you're just using CSS and you know the Unicode value of the icon you want, you can just use those values directly like below:
```css
.my-Icon::before {
  content: '\E707'; /* Unicode for ms-Icon--MapPin */
}
```

All approaches are valid and will work, but I'd recommend either the first or second.

I'll go ahead and close this for now, but feel free to reopen if this doesn't address your needs. Thanks!
