### ISSUE TITLE
On the Fabric Icons help page show the full css class under icon instead of having to hover

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-ui-fabric-core#925]
Just show css class directly in the help page under the icon. Currently you have to hover to see the name of the icon and it's harder to find one.

Also put the full class name so devs can just quickly cut/paste

ms-Icon--DoubleChevronDown

**Comment by mikewheaton** [comment]
This is a design tradeoff between showing as many icons as possible and ensuring their names are readable.

By showing only the name of the icon you're hovering over, we have room to display the name:

![image](https://cloud.githubusercontent.com/assets/1382445/23312607/3747fcc8-fa6f-11e6-8fb7-50cb8d0f3f5c.png)

Whereas if we were to show the names at all times, we end up with overlapping names:

![image](https://cloud.githubusercontent.com/assets/1382445/23312529/f53e9bde-fa6e-11e6-9c39-1c119de3678b.png)

The full class name is not used for the React components, which typically take `iconName` as a prop. Including it would also cause more layout issues due to the limited space:

![image](https://cloud.githubusercontent.com/assets/1382445/23312681/6ea590b8-fa6f-11e6-8b7b-f0befb67f183.png)

One solution we've considered is that clicking on an icon could copy the name (or possibly the full class name) to the clipboard. To make this discoverable we'd need a copy icon next to the name, something like this:

![image](https://cloud.githubusercontent.com/assets/1382445/23312867/2a362e64-fa70-11e6-9a24-48c7fcc5e884.png)

Then it's a question of where best to place this icon and whether its purpose is clear. We don't have plans to revisit this right now, but now that the Fabric website is open source ([GitHub](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/apps/fabric-website)) we'd certainly welcome a pull request and could run it by the design team.

**Comment by jbarr33** [comment]
Ok, no problem.  Just giving feedback that as a help page for devs it is not easy to use. Devs should be able to load the page use the browser "find" and jump right to the icon.  Right now browser "find" does find the icon but since the text does not show you can't tell what it is finding.  Spacing can be handled with CSS wrapping.  Bootstrap site is a good example. Sorry, no time to do pull request.
