### ISSUE TITLE
Documentation: Provide downloads and documentation for self-hosting web and icon fonts

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-core#982]
We've clarified with legal that the [Fabric assets license](https://static2.sharepointonline.com/files/fabric/assets/license.txt) covers hosting a copy of the web and icon fonts on your own server, for scenarios where referencing our CDN is not possible. What we haven't done is document the best way to override the font-face definitions, or where to download a copy of these files from.

**Comment by purtuga** [comment]
@mikewheaton - Glad to see this item here....
I have had several banking and government organizations ask me for a version of my SharePoint Kanban Board ([here](https://paultavares.wordpress.com/my-things/myboard-a-sharepoint-kanban-task-management-system/)) that is 100% hosted on their internal networks due to the restrictions around the sensitive data they handle, so I'm very interested in this.   

Since my project is using webpack, I was going to try and package it up with myself by using webpack "style" loader, which I think does give you the option to pull in images/fonts as base64 encoded strings.... but if you come up with an alternative, then perhaps I will follow your guidelines on how to achieve this.  Have you done any more work on this that you can share?

(Ps. I'm running with an older version of ui-fabric-core, so I'm hoping the instructions can still be applied if you do have something).

/Paul

**Comment by mikewheaton** [comment]
The icon fonts can now be downloaded from the Resources page: https://developer.microsoft.com/en-us/fabric#/resources
